name: main

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Use Go 1.17.5
              uses: actions/setup-go@v2
              with:
                  go-version: 1.17.5

            - run: make fmt
            - run: git diff --name-only --exit-code

            - run: make lint

            - run: make
            - run: ./bin/corsola -hello -count=3
