name: main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        name: Go — Prepare
        with:
          go-version: ^1.20

      - run: |
          make fmt
          git diff --name-only --exit-code

      - run: make lint

      - run: make test
